//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSPTPLWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceCategory
    {
        public Nullable<int> comp_id { get; set; }
        public int attcat_id { get; set; }
        public string name { get; set; }
        public string shortName { get; set; }
        public Nullable<int> otFormula_id { get; set; }
        public Nullable<int> minOTmin { get; set; }
        public Nullable<int> maxOTmin { get; set; }
        public Nullable<int> graceLateMin { get; set; }
        public Nullable<int> graceEarlyMin { get; set; }
        public Nullable<bool> isWeekOffDay1 { get; set; }
        public Nullable<int> weekOffDay1 { get; set; }
        public Nullable<bool> isWeekOffDay2 { get; set; }
        public Nullable<int> weekOffDay2 { get; set; }
        public Nullable<bool> weekOffDay2_1 { get; set; }
        public Nullable<bool> weekOffDay2_2 { get; set; }
        public Nullable<bool> weekOffDay2_3 { get; set; }
        public Nullable<bool> weekOffDay2_4 { get; set; }
        public Nullable<bool> weekOffDay2_5 { get; set; }
        public Nullable<bool> consEarlyPunch { get; set; }
        public Nullable<bool> consLateGoPunch { get; set; }
        public Nullable<bool> deductBreak { get; set; }
        public Nullable<int> cal_HD_WD_LT_Min { get; set; }
        public Nullable<int> cal_AB_WD_LT_Min { get; set; }
        public Nullable<int> cal_PD_HD_WD_LT_Min { get; set; }
        public Nullable<int> cal_PD_AB_WD_LT_Min { get; set; }
        public Nullable<bool> isAbs_Prefix_Day_Abs { get; set; }
        public Nullable<bool> isAbs_Suffix_Day_Abs { get; set; }
        public Nullable<bool> isAbs_Prefix_Suffix_Day_Abs { get; set; }
        public Nullable<bool> isHalfDayLateDays { get; set; }
        public Nullable<int> calHalfDayLateDays { get; set; }
        public Nullable<bool> isAbsentLateDays { get; set; }
        public Nullable<int> calAbsentLateDays { get; set; }
        public Nullable<bool> isHalfDayByLate { get; set; }
        public Nullable<int> calHalfDayByMin { get; set; }
        public Nullable<bool> isHalfDayByEarly { get; set; }
        public Nullable<int> calHalfDayByEarlyMin { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> create_dtm { get; set; }
        public Nullable<System.DateTime> update_dtm { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> updated_by { get; set; }
    }
}
