//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSPTPLWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInfo
    {
        public Nullable<int> comp_id { get; set; }
        public int emp_id { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string birthPlace { get; set; }
        public string bloodGroup { get; set; }
        public string fatherName { get; set; }
        public string montherName { get; set; }
        public string panNo { get; set; }
        public string aadhaarNo { get; set; }
        public string esicNo { get; set; }
        public string pfNo { get; set; }
        public string pfScheme { get; set; }
        public Nullable<System.DateTime> joiningDate { get; set; }
        public Nullable<System.DateTime> confirmDate { get; set; }
        public Nullable<System.DateTime> resignDate { get; set; }
        public string status { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> create_dtm { get; set; }
        public Nullable<System.DateTime> update_dtm { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> updated_by { get; set; }
    }
}
