//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSPTPLWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePayHeader
    {
        public Nullable<int> comp_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public int pay_id { get; set; }
        public string payType { get; set; }
        public string bankName { get; set; }
        public string bankAcctNo { get; set; }
        public string bankIFSE { get; set; }
        public Nullable<System.DateTime> effectiveFrom { get; set; }
        public Nullable<System.DateTime> effectiveTo { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> create_dtm { get; set; }
        public Nullable<System.DateTime> update_dtm { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> updated_by { get; set; }
    }
}
