//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSPTPLWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeave
    {
        public Nullable<int> comp_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public int leave_id { get; set; }
        public Nullable<System.DateTime> fromDate { get; set; }
        public Nullable<System.DateTime> toDate { get; set; }
        public string leaveReason { get; set; }
        public string leaveStatus { get; set; }
        public string rejReason { get; set; }
        public Nullable<int> apprvedBy { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> create_dtm { get; set; }
        public Nullable<System.DateTime> update_dtm { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> updated_by { get; set; }
    }
}
