//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSPTPLWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int emp_id { get; set; }
        public Nullable<int> comp_id { get; set; }
        public Nullable<int> loc_id { get; set; }
        public string fname { get; set; }
        public string mname { get; set; }
        public string lname { get; set; }
        public Nullable<int> deviceCode { get; set; }
        public Nullable<int> deviceEmpCode { get; set; }
        public Nullable<int> emptype_id { get; set; }
        public Nullable<int> vend_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> dept_id { get; set; }
        public Nullable<int> team_id { get; set; }
        public Nullable<int> desig_id { get; set; }
        public Nullable<int> leaveGroup_id { get; set; }
        public Nullable<int> grade_id { get; set; }
        public Nullable<int> shift_id { get; set; }
        public Nullable<int> attcat_id { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> create_dtm { get; set; }
        public Nullable<System.DateTime> update_dtm { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> updated_by { get; set; }
    }
}
