//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSPTPLWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeNominee
    {
        public Nullable<int> comp_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public int nominee_id { get; set; }
        public string nomineeName { get; set; }
        public string perAddress { get; set; }
        public string mobNo { get; set; }
        public string mobNo1 { get; set; }
        public string whatsupNo { get; set; }
        public string primEmail { get; set; }
        public string alterEmail { get; set; }
        public string relation { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> create_dtm { get; set; }
        public Nullable<System.DateTime> update_dtm { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> updated_by { get; set; }
    }
}
