//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSPTPLWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public Nullable<int> comp_id { get; set; }
        public int shift_id { get; set; }
        public string name { get; set; }
        public string shortName { get; set; }
        public Nullable<System.TimeSpan> beginTime24 { get; set; }
        public Nullable<System.TimeSpan> endTime24 { get; set; }
        public Nullable<bool> berak1 { get; set; }
        public Nullable<System.TimeSpan> b1beginTime24 { get; set; }
        public Nullable<System.TimeSpan> b1endTime24 { get; set; }
        public Nullable<bool> berak2 { get; set; }
        public Nullable<System.TimeSpan> b2beginTime24 { get; set; }
        public Nullable<System.TimeSpan> b2endTime24 { get; set; }
        public Nullable<bool> isFlexShift { get; set; }
        public Nullable<int> punchBeginBeforeMin { get; set; }
        public Nullable<int> punchEndAfterMin { get; set; }
        public Nullable<int> graceTimeMin { get; set; }
        public Nullable<bool> partialDaysOn { get; set; }
        public Nullable<int> partialDay { get; set; }
        public Nullable<System.TimeSpan> partialDayBegin { get; set; }
        public Nullable<System.TimeSpan> partialDayEnd { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> create_dtm { get; set; }
        public Nullable<System.DateTime> update_dtm { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> updated_by { get; set; }
    }
}
